### PR TITLE
Minor lint fixes and typos

### PR DESCRIPTION
**Pull request by harry-wood**
Fix some minor code lint: Swap tab characters for spaces. Remove trailing whitespace on the end of lines. Standard newline on the end of file.

(This is all minor stuff, although these particular whitespace things make working with code difficult because my IDE will auto-fix them, so it feels a lot tidier to fix them all at once like this)

\+ Fix a few typos in comments.

### CODE REVIEW

**Comment by harry-wood** [comment]
I thought I'd raise this quick PR to check if this fork is being maintained / welcoming development?

I'm interested in making some improvements here because I'm trying to run a fluxbb import to discourse which uses this code, and I'm seeing some issues / missing features.

I'm not clear why discourse uses this fork and not the [rikkit/ruby-bbcode-to-md](https://github.com/rikkit/ruby-bbcode-to-md) gem source repo, although the tests don't run for me over on that repo, so maybe it's a good thing.

**Comment by Firefishy** [comment]
@nlalonde This look ok to you? Any chance of a merge if good? 

We have a few other improvements for [ruby-bbcode-to-md](https://github.com/nlalonde/ruby-bbcode-to-md) and discourse fluxBB importer lined up.

**Comment by Firefishy** [comment]
@harry-wood I think this PR should be closed, everything from here is already in #6

**Comment by harry-wood** [comment]
Yes I thought this would be a quick and easy one to merge, but for the sake of clarity maybe it's best if I just leave my big PR open

**Pull request closed without merging**
